HelloDjango/HelloDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

###
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('forum/', include('forum.urls')),
    path('', include('home.urls')),
    path('project/', include('project.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HelloDjango/blog/urls.py
from django.urls import path
from . import views
# from .views import post_detail, post_list


urlpatterns = [
    path('<slug:slug>', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('del_review/<int:pk>/', views.DelReview.as_view(), name='del_comment'),
    path('category/<slug:slug>/', views.post_list, name='category_detail'),
]

HelloDjango/forum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ThemeList.as_view(), name='theme_list'),
    path('<slug:slug>/', views.ThemeDetail.as_view(), name='theme_detail'),
    path('comment/<int:pk>/', views.AddComment.as_view(), name='add_comment'),
    path('del_comment/<int:pk>/', views.DelComment.as_view(), name='del_comment_forum'),
]

HelloDjango/forum/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField


class Theme(models.Model):
    """Тема"""
    author = models.ForeignKey(User, on_delete=models.SET_NULL, default=User, null=True, verbose_name='Автор')
    title = models.CharField('Заголовок темы', max_length=500)
    preview = models.TextField('Отрывок', max_length=700)
    body = RichTextUploadingField('Тело темы (Начало не должно иметь быть заголовком или картинкой - только обычное форматирование)')
    url = models.SlugField('URL темы', max_length=100, unique=True)
    draft = models.BooleanField('Опубликовать?', default=True)
    pub_date = models.DateTimeField('Дата публикации', default=datetime.now)
    like = models.PositiveSmallIntegerField('Количество лайков', default=0)
    show_count = models.PositiveSmallIntegerField('Количество просмотров', default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('theme_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'
        ordering = ['-pub_date']


class Comment(models.Model):
    """Ответ на форуме"""
    email = models.EmailField()
    name = models.CharField('Имя автора', max_length=100)
    text = RichTextUploadingField('Сообщение', max_length=7000)
    theme = models.ForeignKey(Theme, verbose_name='Тема', on_delete=models.CASCADE)
    answer_for = models.ForeignKey('self', verbose_name='Ответ на сообщение от', on_delete=models.SET_NULL, blank=True, null=True)
    pub_date = models.DateTimeField('Дата публикации', default=datetime.now, blank=True)
    draft = models.BooleanField('Опубликовать?', default=True)
    like = models.PositiveSmallIntegerField('Количество лайков', default=0)

    def __str__(self):
        return f"{self.name} - {self.theme}"

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'
        ordering = ['-pub_date']

HelloDjango/project/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime

from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

from forum.models import Theme
from user.models import Company

from .functions import path_and_rename


class Data(models.Model):
    """цифровые показатели"""
    name = models.CharField('Наименование показателя', max_length=300)
    number = models.CharField('Значение', max_length=30, help_text='Например, 80%')
    deta_int = models.PositiveSmallIntegerField('Значение шкалы', default=0, help_text='Значение шкалы от 1 до 100')
    order = models.PositiveSmallIntegerField('Порядковый номер', default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Показатель'
        verbose_name_plural = 'Показатели'
        ordering = ['order']


class Benefits(models.Model):
    """Преимущества проекта"""
    title = models.CharField('Заголовок', max_length=200)
    text = models.TextField('Описание')
    icon = models.TextField('Иконка', help_text='Выбрать на сайте https://www.icofont.com/icons')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Преимущество'
        verbose_name_plural = 'Преимущества'


class Structure(models.Model):
    """Структура проекта"""
    title = models.CharField('Заголовок', max_length=200)
    short_title = models.CharField('Короткий заголовок', max_length=100,
                                   help_text='Заголовок, который будет под иконкой')
    icon = models.TextField('Иконка', help_text='Выбрать на сайте https://www.icofont.com/icons')
    short_description = RichTextUploadingField('Короткое описание', max_length=2000, help_text='Будет на странице проекта')
    short_description_seo = models.TextField('Описание для CEO (необязательно)', max_length=500, blank=True)
    description = RichTextUploadingField('Полное описание')
    slug = models.SlugField('Slug', max_length=100, unique=True, help_text='Ссылка. Писать на латинице и без пробелов _')
    order = models.PositiveSmallIntegerField('Порядковый номер')
    image = models.ImageField('Картинка', upload_to=path_and_rename("projects/", 'structure'))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('structure_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Структура проекта'
        ordering = ['order']


class Questions(models.Model):
    question = models.CharField('Вопрос', max_length=500)
    answer = models.TextField('Ответ', max_length=1000)
    order = models.PositiveSmallIntegerField('Порядковый номер', help_text='Необходим для сортировки вопросов')

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Вопрос и ответ'
        verbose_name_plural = 'Вопросы и ответы'
        ordering = ['order']


class Review(models.Model):
    name = models.CharField('Имя', max_length=500)
    text = models.TextField('Тексты отзыва или мнения', max_length=2000)
    position = models.CharField('Дополнительно', max_length=500, help_text='Например: должность')

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = 'Отзыв или мнение'
        verbose_name_plural = 'Отзывы и мнения'


class Project(models.Model):
    """Тема"""
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, default=User, null=True, verbose_name='Компания')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, default=User, null=True, verbose_name='Пользователь')
    name = models.CharField('Название проекта', max_length=200)
    short_description = models.TextField('Краткое описание проекта', max_length=700,
                                         help_text='Будет отображаться в списке проектов')
    title = models.CharField('Заголовок проекта', max_length=200, help_text='Заголовок черного цвета')
    title_grey = models.CharField('Заголовок проекта серый', max_length=200, help_text='Заголовок серого цвета')
    presentation = models.FileField('Презентация проекта в формате pdf',
                                     upload_to=path_and_rename("projects/", 'presentation'), blank=True)
    body = models.TextField('Крaткое описание проекта', max_length=700,
                                         help_text='Будет отображаться в списке проектов')
    description_first_title = models.CharField('Описание 1 - Заголовок', max_length=30)
    description_first = RichTextUploadingField('Описание 1', max_length=2000)
    description_second_title = models.CharField('Описание 2 - Заголовок', max_length=30)
    description_second = RichTextUploadingField('Описание 2', max_length=2000)
    video_title = models.CharField('Заголовок для блока видео', max_length=300)
    video_url = models.URLField('Ссылка на видео', max_length=200)
    benefits = models.ManyToManyField(Benefits, blank=True, verbose_name='Преимуществa')
    data = models.ManyToManyField(Data, blank=True, verbose_name='Показатели',
                                  related_name='title')
    structure_element = models.ManyToManyField(Structure,
                                               verbose_name='Структура проекта')
    questions = models.ManyToManyField(Questions, blank=True,
                                               verbose_name='Вопросы и ответы')
    reviews = models.ManyToManyField(Review, blank=True,
                                               verbose_name='Отзывы или мнения')
    order = models.PositiveSmallIntegerField('Порядковый номер проекта', blank=False,
                                             help_text='Необходим для сортировки проектов')
    slug = models.SlugField('Slug проекта', max_length=100, unique=True,
                            help_text='Должен быть уникальным, только на латинице, вместо пробелов использовать _')
    forum_theme = models.ForeignKey(Theme, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Тема на форуме')
    draft = models.BooleanField('Опубликовать?', default=True)
    pub_date = models.DateTimeField('Дата публикации', default=datetime.now)
    show_count = models.PositiveSmallIntegerField('Количество просмотров', default=0)
    image = models.ImageField('Картинка проекта', upload_to=path_and_rename("projects/", 'project'),
                              help_text='Будет отображаться в списке проектов')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        ordering = ['order']

HelloDjango/forum/forms.py
from urllib import request

from django import forms
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User

from .models import Comment


class CommentForm(forms.ModelForm):
    """Форма Ответов на форуме"""
    class Meta:
        model = Comment
        fields = ('name', 'email', 'text', 'answer_for')

        widgets = {
            'text': CKEditorWidget(attrs={'id': 'f-text', 'required': '', 'placeholder': 'Ваше сообщение *'}),
            'name': forms.TextInput(attrs={'id': 'name', 'required': '', 'placeholder': 'Ваше имя *'}),
            'email': forms.TextInput(attrs={'id': 'email', 'required': '', 'placeholder': 'Email *'}),
            'answer_for': forms.TextInput(attrs={'id': 'answer_for', 'type': 'hidden'})
        }
#
# class CommentForm(forms.Form):
#     text = forms.CharField(widget=CKEditorWidget, label='')
#
#     text.widget.attrs.update({'id': 'post-text'})

HelloDjango/forum/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.views.generic import View

from .models import Theme, Comment
from .forms import CommentForm

from contact.models import Bot
import requests


class ThemeList(View):
    """Вывод списка тем"""
    def get(self, request):
        themes = Theme.objects.filter(draft=True)
        paginator = Paginator(themes, 10)
        page_number = request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        is_paginated = page.has_other_pages()

        if page.has_previous():
            prev_url = '?page={}'.format(page.previous_page_number())
        else:
            prev_url = ''

        if page.has_next():
            next_url = '?page={}'.format(page.next_page_number())
        else:
            next_url = ''

        return render(request, 'forum/theme_list.html', {
            'page': page,
            'is_paginated': is_paginated,
            'next_url': next_url,
            'prev_url': prev_url})


class ThemeDetail(View):
    """Страница темы"""
    def get(self, request, slug):
        theme = Theme.objects.get(url=slug)
        theme_list = Theme.objects.all()
        body_first_word = theme.body[3]
        body = theme.body[4:]
        comments = Comment.objects.filter(theme__url=slug)
        paginator = Paginator(comments, 10)
        page_number = request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        is_paginated = page.has_other_pages()
        req_user = request.user

        form = CommentForm(request.POST)

        if page.has_previous():
            prev_url = '?page={}'.format(page.previous_page_number())
        else:
            prev_url = ''

        if page.has_next():
            next_url = '?page={}'.format(page.next_page_number())
        else:
            next_url = ''

        return render(request, 'forum/theme_detail.html', {
            'page': page,
            'is_paginated': is_paginated,
            'next_url': next_url,
            'prev_url': prev_url,
            'theme': theme,
            'theme_list': theme_list,
            'body_first_word': body_first_word,
            'body': body,
            'form': form,
            'req_user': req_user,
        })


class AddComment(View):
    """Ответ на форуме"""
    def post(self, request, pk):
        form = CommentForm(request.POST)
        bot = Bot.objects.get(number=1)

        if form.is_valid():
        #  Отправляем данные в телеграм
            url = f'{bot.url}' + 'sendMessage'
            chat_id = bot.chat_id
            name = request.POST.get('name')  # Поучаем имя пользователя, который оставил сообщение
            title = request.POST.get('title')  # Получаем заголовок страницы
            comment_text = request.POST.get('text')  # Получаем текст сообщения
            comment_url = request.POST.get('url')  # Получаем адрес страницы форума
            text = f'Новое сообщение на форуме \n \n Пользователь: {name} \n ' \
                   f'Тема: {title} \n Сообщение: \n {comment_text} \n \n Адрес: {comment_url}'
            answer = {'chat_id': chat_id, 'text': text}
            requests.post(url, answer)

            # Сохраняем форму
            form = form.save(commit=False)
            form.theme_id = pk
            if request.POST.get('answer_for', None):
                form.answer_for_id = int(request.POST.get('answer_for'))
            form.save()            


class DelComment(View):

    """Удаление сообщений на форуме"""
    def post(self, request, pk):
        comment_id = int(request.POST.get('id'))
        comment = Comment.objects.get(id=comment_id)

        comment.delete()
        return comment

HelloDjango/forum/templates/forum/base_forum.html
{% extends 'base.html' %}

HelloDjango/forum/templates/forum/theme_detail.html
{% extends 'forum/base_forum.html' %}
{% load static %}

{% block title %}
{{ theme.title }} | {{ block.super }}
{% endblock %}

{% block description %}
{{ theme.preview }}
{% endblock %}



{% block content %}
<!-- Заголовок и крошки -->
<div class="page-header dtable text-center"
    style="background-image: url({% static 'assets/images/bg-page-header.jpg' %});">
    <div class="dcell">
        <div class="container">
            <h1 class="page-title">{{ theme.title }}</h1>
            <ul id="breadcrumbs" class="breadcrumbs">
                <li><a href="/">Главная</a></li>
                <li><a href="{% url 'theme_list' %}">Форум</a></li>
                <li class="active">{{ theme.title }}</li>
            </ul>
        </div>
    </div>
</div>
<!-- // Заголовок и крошки // -->
<div class="entry-content">
    <div class="container">
        <div class="row">
            <!-- Автор и категории -->
            <aside class="widget-area primary-sidebar col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <div class="ot-accordions accordions-gradient">
                    <div class="acc-item text-center">
                        <span class="acc-toggle">Автор темы<i class="down flaticon-arrow-pointing-to-down"></i><i
                                class="up flaticon-arrow-pointing-to-up"></i></span>
                        <div class="acc-content">
                            <div class="author-widget_image-wrapper">
                                <img class="author-widget_image border-img" src="{{ theme.author.profile.avatar.url }}"
                                    alt="{{ theme.author.profile.name }}">
                            </div>
                            <h5 class="author-widget_title color-white mt-25"><a
                                    href="{{ theme.author.profile.get_absolute_url }}"> {{ theme.author.profile.name }}
                                </a></h5>
                            <p class="author-widget_text">{{ theme.author.profile.slogan }}</p>
                            <div class="author-widget_social">
                                {% if theme.author.profile.vk %}
                                <a href="{{ theme.author.profile.vk }}" class="facebook" target="_blank"><i
                                        class="fab fa-vk"></i></a>
                                {% endif %}
                                {% if theme.author.profile.fb %}
                                <a href="{{ theme.author.profile.fb }}" class="facebook" target="_blank"><i
                                        class="fab fa-facebook-f"></i></a>
                                {% endif %}
                                {% if theme.author.profile.instagram %}
                                <a href="{{ theme.author.profile.instagram }}" class="instagram" target="_blank"><i
                                        class="fab fa-instagram"></i></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="acc-item">
                        <span class="acc-toggle">Другие темы форума<i
                                class="down flaticon-arrow-pointing-to-down"></i><i
                                class="up flaticon-arrow-pointing-to-up"></i></span>
                        <div class="acc-content">
                            <section class="widget widget_categories">
                                <ul>
                                    {% for theme in theme_list %}
                                    <li><a href="{{ theme.get_absolute_url }}"
                                            style="color: #fff;">{{ theme.title }}</a> <span
                                            class="posts-count">({{ theme.comment_set.all.count }} <i
                                                class="flaticon-chat"></i>)</span></li>
                                    {% endfor %}
                                </ul>
                            </section>
                        </div>
                    </div>
                </div>
                <hr>
            </aside>

            <!-- Тема -->
            <article class="post-box col-lg-9 col-md-9 col-sm-12 col-xs-12">
                <div class="post-inner forum-hero">
                    <div class="content-area ">
                        <article class="post-box blog-post">
                            <div class="inner-post no-padding-top">
                                <div class="entry-summary">
                                    <h4>{{ theme.title }}</h4>
                                    <p><span class="drop-cap"><span
                                                class="drop-cap-letter">{{ body_first_word }}</span></span>{% autoescape off %}{{ body }}
                                        {% endautoescape %}</p>
                                </div>
                            </div>
                            {% for project in theme.project_set.all %}
                            <a href="{{ project.get_absolute_url }}" class="octf-btn octf-btn-secondary">Подробнее о
                                проекте</a>
                            {% endfor %}

                            <hr>
                            <div class="entry-meta mt-25">
                                <span class="byline"><a class="url fn n" href="#"><i
                                            class="far fa-thumbs-up"></i>{{ theme.like }}</a></span>
                                <!--                                            <span class="byline"><a class="url fn n" href="#"><i class="far fa-thumbs-down"></i>{{ theme.dislike }}</a></span>-->
                                <span class="posted-on"><i class="flaticon-clock"></i><time
                                        class="entry-date published">{{ theme.pub_date }}</time></span>
                                <span class="comment-num"><i class="flaticon-chat"></i> Ответов:
                                    {{ theme.comment_set.all.count }}</span>
                            </div><!-- .entry-meta -->

                        </article>
                    </div>
                </div>
            </article>
            <!-- // Тема // -->
        </div>
        <!-- Форма ответа -->
        <div id="respond" class="comment-respond forum-form p-relative">
            <i class="icofont-pen-alt-2 icon-absloute"></i>
            <h5 id="reply-title" class="comment-reply-title pb-25">Ваше сообщение: </h5>
            <form action="{% url 'add_comment' theme.id %}" method="post" class="comment-form">
                {% csrf_token %}
                <script type="text/javascript">
                    let csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                </script>
                {{ form.answer_for }}
                <div class="row">
                    <p class="comment-form-author col-md-6">
                        {{ form.name }}
                        <span id="error-name" class="error-text"></span>
                    </p>
                    <p class="comment-form-email col-md-6">
                        {{ form.email }}
                        <span id="error-email" class="error-text"></span>
                    </p>
                </div>
                <div class="pow">
                    {{ form.text }}
                    {{ form.media }}
                    <span id="error-text-id" class="error-text"></span>
                </div>
                <p class="form-submit">
                    <input name="submit" onclick="AjaxAddCommentForum('{{ theme.get_absolute_url }}')" id="submit"
                        class="octf-btn octf-btn-secondary" value="Отправить">
                </p>
            </form>
        </div>
        <!-- // Форма ответа // -->

        <div id="theme-comment-start"></div>
        <span id="reload-forum" onclick="AjaxReload()"><i class="icofont-history"></i> Обновить ленту сообщений</span>
        <br>
        <div class="forum-answers-reload">
            {% for comment in page %}
            <!-- Ответ -->
            <article class="post-box">
                <div class="post-inner forum-hero">
                    <div class="content-area ">
                        <article class="post-box blog-post">
                            <div class="row">
                                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-center">
                                    <!--                                            <div class="author-widget_image-wrapper">-->
                                    <!--                                                <img class="author-widget_image img-circle" src="images/avatar.png" alt="Kate Olson">-->
                                    <!--                                            </div>-->
                                    <h5 class="author-widget_title">{{ comment.name }}</h5>
                                </div>
                                <div class="inner-post no-padding-top col-lg-9 col-md-9 col-sm-12 col-xs-12">
                                    {% if comment.answer_for.name %}
                                    <div class="answer">
                                        Ответ для пользователя <b>{{ comment.answer_for.name }}:</b>
                                        {% autoescape off %}<blockquote class="answer">{{ comment.answer_for.text }}
                                        </blockquote>{% endautoescape %}
                                    </div>
                                    {% endif %}
                                    <div class="entry-summary">
                                        {% autoescape off%} {{ comment.text }} {% endautoescape %}
                                    </div>
                                </div>
                                <div class="entry-meta forum-hero-bottom">
                                    <span class="byline"><a class="url fn n" href="#respond"
                                            onclick="addCommentForum('{{ comment.name }}', '{{ comment.id }}')"><i
                                                class="far fa-comment-dots"></i> Ответить</a></span>
                                    <span class="byline"><a class="url fn n" href="#"><i class="far fa-thumbs-up"></i>
                                            {{ comment.like }}</a></span>
                                    <!--                                        <span class="byline"><a class="url fn n" href="#"><i class="far fa-thumbs-down"></i> {{ comment.dislike }}</a></span>-->
                                    <span class="posted-on"><i class="flaticon-clock"></i> <time
                                            class="entry-date published">{{ comment.pub_date }}</time></span>
                                    {% if request.user.is_staff %}
                                    <a href="{% url 'del_comment_forum' comment.id %}" id="delComm"
                                        style="display: none;"></a>
                                    <buuton href="" onclick="AjaxDelForumComment('{{ comment.id }}')"
                                        class="comment-reply-link scroll-to" style="margin-top: 25px; color: red;">
                                        Удалить</buuton>
                                    {% endif %}
                                </div><!-- .entry-meta -->
                            </div>
                        </article>
                    </div>
                </div>
            </article>
            <!-- // Ответ // -->
            {% endfor %}
        </div>

        <!-- Пагинация -->
        {% include 'includes/paginate.html' %}
        <!-- // Пагинация // -->
    </div>
</div>

<script type="text/javascript" src="{% static 'assets/js/ajax/forum.js' %}"></script>
<script>
    $(document).ready(function () {
        funonload('{{ request.user.profile.name }}', '{{ request.user.email }}');
    })
    function funonload(name, email) {
        document.getElementById("name").value = name;
        document.getElementById("email").value = email;
    }
</script>





{% endblock %}

HelloDjango/forum/templates/forum/theme_list.html
{% extends 'forum/base_forum.html' %}
{% load static %}
{% block title %}
Форум | {{ block.super }}
{% endblock %}
{% block description %}
Выберите интересную для вас тему и выразите свою точку зрения. Здесь также можно обсуждать проекты, которые размещены на
нашем сайте
{% endblock %}

{% block content %}

<div class="page-header dtable text-center"
    style="background-image: url({% static 'assets/images/bg-page-header.jpg' %});">
    <div class="dcell">
        <div class="container">
            <h1 class="page-title">Форум</h1>
            <ul id="breadcrumbs" class="breadcrumbs">
                <li><a href="/">Главная</a></li>
                <li class="active">Форум</li>
            </ul>
        </div>
    </div>
</div>

<div class="forum-list">
    <div class="container">
        <div class="ot-heading left-align p-b35">
            <h2 class="main-heading">Темы форума</h2>
        </div>
        <div class="content-area">
            <div class="blog-list">
                {% for theme in page %}
                <article class="post-box" id="post-list-item">
                    <div class="post-inner">
                        <div class="entry-media">
                            <div class="post-cat">
                                <span class="posted-in forum-btn">
                                    <a href="{{ theme.get_absolute_url }}" rel="category tag">Перейти к обсуждению</a>
                                    {% for project in theme.project_set.all %}
                                    <a href="{{ project.get_absolute_url }}" rel="category tag">О проекте</a>
                                    {% endfor %}
                                </span>
                            </div>
                        </div>
                        <div class="inner-post">
                            <div class="entry-header">
                                <h3 class="entry-title  mt-25"><a
                                        href="{{ theme.get_absolute_url }}">{{ theme.title }}</a></h3>
                            </div><!-- .entry-header -->
                            <div class="entry-summary the-excerpt">
                                <p>{{ theme.preview }}</p>
                            </div><!-- .entry-content -->
                            <div class="entry-meta mt-25">
                                <span class="byline"><a class="url fn n"
                                        href="{{ theme.author.profile.get_absolute_url }}"><i class="flaticon-user"></i>
                                        Автор: {{ theme.author.profile.name }}</a></span>
                                <span class="posted-on">
                                    <i class="flaticon-clock"></i> <time
                                        class="entry-date published">{{ theme.pub_date }}</time>
                                </span>
                                <span class="comment-num"><i class="flaticon-chat"></i> Сообщений:
                                    {{ theme.comment_set.all.count }}</span>
                            </div><!-- .entry-meta -->
                        </div>
                    </div>
                </article>
                {% endfor %}

            </div>
            {% include 'includes/paginate.html' %}
        </div>
    </div>
</div>


{% endblock %}