HelloDjango/HelloDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

###
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('forum/', include('forum.urls')),
    path('', include('home.urls')),
    path('project/', include('project.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HelloDjango/blog/urls.py
from django.urls import path
from . import views
# from .views import post_detail, post_list


urlpatterns = [
    path('<slug:slug>', views.post_list, name='post_list'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('del_review/<int:pk>/', views.DelReview.as_view(), name='del_comment'),
    path('category/<slug:slug>/', views.post_list, name='category_detail'),
]

HelloDjango/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>/', views.UserDetailView.as_view(), name='user_detail'),
    path('company/<slug:slug>/', views.CompanyDetailView.as_view(), name='company_detail'),
]

HelloDjango/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField


class Profile(models.Model):
    """User дополнения"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=User)
    name = models.CharField('ФИО', max_length=500)
    main_phone = models.CharField('Основной номер телефона', max_length=30, blank=True,
                                  help_text='Указывать необязательно. Будет публиковано на сайте')
    second_phone = models.CharField('Дополнительный номер телефона (необязательно)', max_length=30, blank=True,
                                    help_text='Указывать необязательно. Будет публиковано на сайте')
    whatsapp_phone = models.CharField('Номер Whatapp (необязательно)', max_length=30, blank=True,
                                      help_text='Необходимо вместо +7 или 8 указать просто 7. '
                                                'Указывать номер обязательно без пробелов тире и других знаков ')
    mail = models.EmailField('E-mail', blank=True)
    slogan = models.TextField('Слоган', max_length=500)
    bio = RichTextUploadingField('Информация о пользователе')
    professional = models.CharField('Профессия', max_length=200)
    register_date = models.DateTimeField('Дата регистрации', auto_now_add=True, null=True, blank=True)
    vk = models.URLField('Ссылка на профиль ВКонтакте', max_length=200, blank=True)
    fb = models.URLField('Ссылка на профиль Facebook', max_length=200, blank=True)
    instagram = models.URLField('Ссылка на профиль Instagram', max_length=200, blank=True)
    url = models.SlugField('URL', default=User, unique=True)
    avatar = models.ImageField('Аватар', upload_to='files/users/avatars/', help_text='250x250px')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('user_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        ordering = ['-register_date']


class Company(models.Model):
    """Компания"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Администратор компании на сайте', null=True)
    name = models.CharField('Название компании', max_length=500, null=True)
    name_legal = RichTextUploadingField('Реквизиты компании', blank=True)
    address = models.CharField('Адрес компании', max_length=500)
    main_phone = models.CharField('Основной номер телефона', max_length=30, blank=True)
    second_phone = models.CharField('Дополнительный номер телефона (необязательно)', max_length=30, blank=True)
    whatsapp_phone = models.CharField('Номер Whatapp (необязательно)', max_length=30, blank=True,
                                      help_text='Необходимо вместо +7 или 8 указать просто 7. Указывать номер обязательно без пробелов тире и других знаков ')
    mail = models.EmailField('E-mail', blank=True)
    slogan = models.TextField('Слоган', max_length=500)
    about_cooperators = models.TextField('Несколько слов о Вашей команде сотрудников (если она есть)', blank=True)
    bio = RichTextUploadingField('Информация о компании', blank=True)
    specialization = models.CharField('Специализация', max_length=200)
    cooperator = models.ManyToManyField(Profile, verbose_name='Сотрудники', blank=True)
    register_date = models.DateTimeField('Дата регистрации', auto_now_add=True, null=True, blank=True)
    vk = models.URLField('Ссылка на профиль ВКонтакте', max_length=200, blank=True)
    fb = models.URLField('Ссылка на профиль Facebook', max_length=200, blank=True)
    instagram = models.URLField('Ссылка на профиль Instagram', max_length=200, blank=True)
    url = models.SlugField('URL', default=User, unique=True)
    logo = models.ImageField('Логотип', upload_to='files/company/logo/')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('company_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'
        ordering = ['-register_date']

HelloDjango/user/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView


from .models import Profile, Company


class UserDetailView(DetailView):
    model = Profile
    slug_field = 'url'


class CompanyDetailView(DetailView):
    model = Company
    slug_field = 'url'

HelloDjango/user/templates/user/base_user.html
{% extends 'base.html' %}

HelloDjango/user/templates/user/company_detail.html
{% extends 'user/base_user.html' %}
{% block title %}
{{ company.name }} - {{ company.specialization }} | {{ block.super }}
{% endblock %}

{% block description %}
{{ company.bio }}
{% endblock %}

{% block content %}
<section class="p-tb90 particles-js" data-color="#fe4c1c,#00c3ff,#0160e7" data-id="a1">
    <div class="container-fluid">
        <div class="row flex-row">
            <div class="col-md-4 col-xs-12 p-lr30 xs-p-lr15 align-self-center xs-m-b40">
                <img src="{{ company.logo.url }}" alt="">
            </div>
            <div class="col-md-8 col-xs-12 p-l85 p-r70 xs-p-lr15 align-self-center">
                <h6 class="steam-pos">{{ company.specialization }}</h6>
                <h2 class="steam-name">{{ company.name }}</h2>
                <blockquote>{{ company.slogan }}</blockquote>
                <div class="steam-desc blue-shadow">{% autoescape off %} {{ company.bio }} {% endautoescape %}</div>
                <div class="row">
                    <div class="col-md-4 col-sm-6 h-100">
                        <div class="steam-desc h-100 blue-shadow">
                            <ul class="comp_contacts h-100">
                                <h6>Контакты:</h6>
                                {% if company.address %}
                                <li><i class="fas fa-map-marker-alt"></i> {{ company.address }}</li>
                                {% endif %}
                                {% if company.main_phone %}
                                <li><a href="tel:{{ company.main_phone }}"><i class="fas fa-phone"></i>
                                        {{ company.main_phone }}</a></li>
                                {% endif %}
                                {% if company.second_phone %}
                                <li><a href="tel:{{ company.second_phone }}"><i class="fas fa-phone"></i>
                                        {{ company.second_phone }}</a></li>
                                {% endif %}
                                {% if company.whatsapp_phone %}
                                <li><a href="https://wa.me/{{ company.whatsapp_phone }}"><i class="fab fa-whatsapp"></i>
                                        {{ company.whatsapp_phone }}</a></li>
                                {% endif %}
                                {% if company.mail %}
                                <li><a href="mailto:{{ company.mail }}"><i class="far fa-envelope"></i>
                                        {{ company.mail }}</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-8 col-sm-6">
                        <div class="steam-desc blue-shadow">
                            <h6>Реквизиты:</h6>
                            {% autoescape off %} {{ company.name_legal }} {% endautoescape %}
                        </div>
                    </div>
                </div>
                <div class="steam-social">
                    <h6>Мы в социальных сетях: </h6>
                    {% if company.vk %}
                    <a href="{{ company.vk }}" class="facebook" target="_blank"><i class="fab fa-vk"></i></a>
                    {% endif %}
                    {% if company.fb %}
                    <a href="{{ company.fb }}" class="facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    {% endif %}
                    {% if company.instagram %}
                    <a href="{{ company.instagram }}" class="instagram" target="_blank"><i
                            class="fab fa-instagram"></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
<section class="home2-team">
    <div class="container">
        <hr>
        <div class="row p-b40">
            <div>
                <div class="ot-heading left-align col-md-12">
                    <h6><span>Сотрудники компании</span></h6>
                    <h2 class="main-heading">Наша команда</h2>

                    <p>{{ company.about_cooperators }}</p>
                </div>
            </div>
        </div>
        <div class="row mt-25">
            <div class="col-md-12 col-xs-12">
                <div class="team-slider">
                    {% for cooperator in company.cooperator.all %}
                    <div class="team-wrap">
                        <div class="team-thumb">
                            <a href="{{ cooperator.get_absolute_url }}" title="Подробнее" class="my-link">
                                <img src="{{ cooperator.avatar.url }}" alt="{{ cooperator.profile.name }}" width="150px"
                                    height="150px">
                            </a>
                        </div>
                        <div class="team-info">
                            <h4><a href="{{ cooperator.get_absolute_url }}" title="Подробнее"
                                    class="my-link">{{ cooperator.name }}</a></h4>
                            <span>{{ cooperator.professional }}<br>{{ cooperator.slogan }}</span>
                            <div class="team-social">
                                {% if cooperator.vk %}
                                <a href="{{ cooperator.vk }}" class="facebook" target="_blank"><i
                                        class="fab fa-vk"></i></a>
                                {% endif %}
                                {% if cooperator.fb %}
                                <a href="{{ cooperator.fb }}" class="facebook" target="_blank"><i
                                        class="fab fa-facebook-f"></i></a>
                                {% endif %}
                                {% if cooperator.instagram %}
                                <a href="{{ cooperator.instagram }}" class="instagram" target="_blank"><i
                                        class="fab fa-instagram"></i></a>
                                {% endif %}
                                <span class="flaticon-add-1"></span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <hr>
        <div class="row m-t100">
            <div class="col-md-12">
                {% include 'includes/share.html' %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

HelloDjango/user/templates/user/profile_detail.html
{% extends 'user/base_user.html' %}
{% load static %}
{% block title %}
{{ profile.name }} - {{ profile.professional}} | {{ block.super }}
{% endblock %}
{% block description %}
{{ profile.bio }}
{% endblock %}

{% block content %}

<section class="p-t90 particles-js" data-color="#fe4c1c,#00c3ff,#0160e7" data-id="a1">
    <div class="container">
        <div class="row flex-row">
            <div class="col-md-4 col-xs-12 p-lr30 xs-p-lr15 align-self-center xs-m-b40">
                <img src="{{ profile.avatar.url }}" alt="">
            </div>
            <div class="col-md-8 col-xs-12 p-l85 p-r70 xs-p-lr15 align-self-center">
                <h6 class="steam-pos">{{ profile.professional }}</h6>
                <h2 class="steam-name">{{ profile.name }}</h2>
                <blockquote>{{ profile.slogan }}</blockquote>
                <div class="steam-desc blue-shadow">

                    {% autoescape off %} {{ profile.bio }} {% endautoescape %}

                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <div class="blue-shadow my-border p-relative">
                            <i class="icofont-contacts icon-absloute"></i>
                            <ul class="comp_contacts h-100">
                                <h6>Контакты:</h6>

                                {% if profile.main_phone %}
                                <li><a href="tel:{{ profile.main_phone }}"><i class="fas fa-phone"></i>
                                        {{ profile.main_phone }}</a></li>
                                {% endif %}
                                {% if profile.second_phone %}
                                <li><a href="tel:{{ profile.second_phone }}"><i class="fas fa-phone"></i>
                                        {{ profile.second_phone }}</a></li>
                                {% endif %}
                                {% if profile.whatsapp_phone %}
                                <li><a href="https://wa.me/{{ profile.whatsapp_phone }}"><i class="fab fa-whatsapp"></i>
                                        {{ profile.whatsapp_phone }}</a></li>
                                {% endif %}
                                {% if profile.mail %}
                                <li><a href="mailto:{{ profile.mail }}"><i class="far fa-envelope"></i>
                                        {{ profile.mail }}</a></li>
                                {% endif %}

                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="blue-shadow my-border p-relative">
                            <i class="icofont-ui-home icon-absloute"></i>

                            {% for company in profile.company_set.all %}
                            <h6 class="steam-info">Компания:</h6>
                            <h6 class="steam-info"><a href="{{ company.get_absolute_url }}">{{ company.name }}</a></h6>
                            <p>{{ company.slogan }}</p>
                            {% endfor %}

                            <h6 class="steam-info"></h6>
                            <p class="m-b30"></p>
                        </div>
                    </div>
                </div>
                <div class="steam-social">
                    <h6>Я в социальных сетях:</h6>

                    {% if profile.vk %}
                    <a href="{{ profile.vk }}" class="facebook" target="_blank"><i class="fab fa-vk"></i></a>
                    {% endif %}
                    {% if profile.fb %}
                    <a href="{{ profile.fb }}" class="facebook" target="_blank"><i class="fab fa-facebook-f"></i></a>
                    {% endif %}
                    {% if profile.instagram %}
                    <a href="{{ profile.instagram }}" class="instagram" target="_blank"><i
                            class="fab fa-instagram"></i></a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <!-- Share -->
    <div class="p-t90 blog-grid-content">
        <div class="container">
            <hr>
            {% include 'includes/share.html' %}
        </div>
    </div>
    <!-- // Посты // -->
</section>

{% endblock %}